# Generated by Django 3.1.4 on 2021-03-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnifyDataRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('device_sn', models.CharField(blank=True, max_length=128, null=True)),
                ('index', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('meas_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '一体化数据',
                'verbose_name_plural': '一体化数据',
                'db_table': 't_unify_data_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('device_sn', models.CharField(blank=True, max_length=128, null=True)),
                ('scan_time', models.CharField(blank=True, max_length=32, null=True)),
                ('scan_points', models.CharField(blank=True, max_length=32, null=True)),
                ('start_angle', models.CharField(blank=True, max_length=32, null=True)),
                ('step', models.CharField(blank=True, max_length=32, null=True)),
                ('angle', models.CharField(blank=True, max_length=32, null=True)),
                ('range', models.CharField(blank=True, max_length=32, null=True)),
                ('turns_flag', models.IntegerField()),
                ('times', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': '轮廓数据表',
                'verbose_name_plural': '轮廓数据表',
                'db_table': 't_collect_raw',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('device_sn', models.CharField(max_length=128, verbose_name='设备编号')),
                ('timestamp', models.DateTimeField(verbose_name='测量的时间戳')),
                ('convergence', models.FloatField(max_length=64, verbose_name='收敛值')),
                ('sedimentation', models.FloatField(max_length=64, verbose_name='沉降值')),
            ],
            options={
                'verbose_name': '数据处理结果表',
                'verbose_name_plural': '数据处理结果表',
                'db_table': 't_result',
            },
        ),
    ]
