# Generated by Django 3.1.4 on 2020-12-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('device_sn', models.CharField(max_length=128, verbose_name='设备编号')),
                ('angle', models.FloatField(max_length=64, verbose_name='监测角度')),
                ('range', models.FloatField(max_length=64, verbose_name='监测距离')),
                ('turns_flag', models.IntegerField(verbose_name='圈数标志')),
                ('times', models.IntegerField(verbose_name='次数编号')),
                ('timestamp', models.DateTimeField(verbose_name='测量的时间戳')),
                ('section', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_manage.section', verbose_name='所属断面')),
            ],
            options={
                'verbose_name': '轮廓记录表',
                'verbose_name_plural': '轮廓记录表',
                'db_table': 't_outline',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('device_sn', models.CharField(max_length=128, verbose_name='设备编号')),
                ('timestamp', models.DateTimeField(verbose_name='测量的时间戳')),
                ('convergence', models.FloatField(max_length=64, verbose_name='收敛值')),
                ('sedimentation', models.FloatField(max_length=64, verbose_name='沉降值')),
                ('section', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_manage.section', verbose_name='所属断面')),
            ],
            options={
                'verbose_name': '数据处理结果表',
                'verbose_name_plural': '数据处理结果表',
                'db_table': 't_result',
            },
        ),
    ]
