# Generated by Django 3.1.4 on 2020-12-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('device_sn', models.CharField(max_length=128, verbose_name='设备编号')),
                ('scan_resolution', models.FloatField(max_length=64, verbose_name='扫面分辨率')),
                ('start_angle', models.FloatField(max_length=64, verbose_name='起始角度')),
                ('end_angle', models.FloatField(max_length=64, verbose_name='终止角度')),
                ('re_times', models.IntegerField(verbose_name='单点重复测量次数')),
                ('turns_flag', models.IntegerField(verbose_name='圈数标志')),
                ('cycle', models.FloatField(max_length=64, verbose_name='采集周期')),
            ],
            options={
                'verbose_name': '设置参数表',
                'verbose_name_plural': '设置参数表',
                'db_table': 't_param',
            },
        ),
    ]
