# Generated by Django 3.1.4 on 2021-03-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('device_sn', models.CharField(max_length=128)),
                ('soft_ver', models.CharField(blank=True, max_length=32, null=True)),
                ('firm_ver', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.IntegerField()),
                ('control', models.IntegerField(blank=True, null=True)),
                ('upfile', models.CharField(blank=True, max_length=100, null=True)),
                ('to_softver', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': '管理-设备列表',
                'verbose_name_plural': '管理-设备列表',
                'db_table': 't_device',
            },
        ),
        migrations.CreateModel(
            name='ZeroOffset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('zero_offset', models.CharField(blank=True, max_length=32, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_install.device')),
            ],
            options={
                'verbose_name': '设置-零偏参数',
                'verbose_name_plural': '设置-零偏参数',
                'db_table': 't_zero_offset',
            },
        ),
        migrations.CreateModel(
            name='UnifyParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('meas_intvl', models.CharField(blank=True, max_length=32, null=True)),
                ('up_intvl', models.CharField(blank=True, max_length=32, null=True)),
                ('meas_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('server_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('server_bak_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('server_port', models.CharField(blank=True, max_length=32, null=True)),
                ('server_bak_port', models.CharField(blank=True, max_length=32, null=True)),
                ('bak_use_date', models.DateTimeField(blank=True, null=True)),
                ('server_bak_switch', models.IntegerField()),
                ('network_status', models.CharField(blank=True, max_length=32, null=True)),
                ('range', models.CharField(blank=True, max_length=32, null=True)),
                ('addr_storage', models.CharField(blank=True, max_length=32, null=True)),
                ('addr_upload', models.CharField(blank=True, max_length=32, null=True)),
                ('battery_volt', models.CharField(blank=True, max_length=32, null=True)),
                ('charge_state', models.CharField(blank=True, max_length=32, null=True)),
                ('firm_ver', models.CharField(blank=True, max_length=32, null=True)),
                ('init_val', models.CharField(blank=True, max_length=32, null=True)),
                ('power_type', models.CharField(blank=True, max_length=32, null=True)),
                ('soft_ver', models.CharField(blank=True, max_length=32, null=True)),
                ('meas_num', models.CharField(blank=True, max_length=32, null=True)),
                ('reserve', models.CharField(blank=True, max_length=32, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_install.device')),
            ],
            options={
                'verbose_name': '一体化参数',
                'verbose_name_plural': '一体化参数',
                'db_table': 't_unify_param',
            },
        ),
        migrations.CreateModel(
            name='MeasureArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('re_times', models.CharField(max_length=64)),
                ('scan_resolution', models.CharField(max_length=64)),
                ('start_angle', models.CharField(max_length=64)),
                ('end_angle', models.CharField(max_length=64)),
                ('turns_flag', models.CharField(blank=True, max_length=64, null=True)),
                ('cycle', models.CharField(blank=True, max_length=64, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_install.device')),
            ],
            options={
                'verbose_name': '设置-测量区段',
                'verbose_name_plural': '设置-测量区段',
                'db_table': 't_measure_area',
            },
        ),
        migrations.CreateModel(
            name='DevicePid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('angle_p', models.CharField(blank=True, max_length=32, null=True)),
                ('angle_i', models.CharField(blank=True, max_length=32, null=True)),
                ('speed_p', models.CharField(blank=True, max_length=32, null=True)),
                ('speed_i', models.CharField(blank=True, max_length=32, null=True)),
                ('max_acc', models.CharField(blank=True, max_length=32, null=True)),
                ('max_speed', models.CharField(blank=True, max_length=32, null=True)),
                ('max_angle', models.CharField(blank=True, max_length=32, null=True)),
                ('angle_err', models.CharField(blank=True, max_length=32, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_install.device')),
            ],
            options={
                'verbose_name': '设置-pid参数',
                'verbose_name_plural': '设置-pid参数',
                'db_table': 't_device_pid',
            },
        ),
    ]
