# Generated by Django 3.1.4 on 2021-03-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_install', '0001_initial'),
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_manage.section'),
        ),
    ]
