# Generated by Django 3.1.4 on 2021-01-19 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tunnel_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='隧道边幅名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.CharField(max_length=32, verbose_name='位置详情'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=64, verbose_name='断面名称'),
        ),
    ]
