# Generated by Django 3.1.4 on 2021-01-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_auto_20210119_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='name',
        ),
    ]
