# Generated by Django 3.1.4 on 2021-01-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_auto_20210121_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
    ]
