# Generated by Django 3.1.4 on 2021-01-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0005_remove_user_real_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='operatecompany',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='position',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
    ]
