# Generated by Django 3.1.4 on 2021-03-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, verbose_name='预警名')),
                ('level', models.IntegerField(choices=[(4, 'Ⅳ级：一般'), (3, 'Ⅲ级：较重'), (2, 'Ⅱ级：严重'), (1, 'Ⅰ级：特别严重')], default=4, verbose_name='预警级别')),
                ('notify_obj', models.CharField(max_length=128, verbose_name='通知对象')),
                ('desc', models.CharField(max_length=256, verbose_name='预警信息描述')),
                ('project', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_manage.project', verbose_name='所属工程')),
            ],
            options={
                'verbose_name': '预警信息表',
                'verbose_name_plural': '预警信息表',
                'db_table': 't_warning',
            },
        ),
    ]
