# Generated by Django 3.1.4 on 2021-01-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warning',
            name='is_delete',
        ),
    ]
